# Generated by Django 4.1.3 on 2022-11-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=120, null=True, verbose_name='Владелец ответа')),
                ('profile', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('data_creating', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=120, null=True, verbose_name='Владелец вопроса')),
                ('profile', models.ImageField(upload_to='', verbose_name='Aватар')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('data_creating', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question_app.question', verbose_name='Вопрос'),
        ),
    ]
