# Generated by Django 4.1.3 on 2022-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[(1, 'offline'), (2, 'online')], max_length=255, verbose_name='Формат обучения'),
        ),
    ]
