# Generated by Django 4.1.3 on 2022-11-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_course_certificate_alter_course_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='format',
            new_name='time_study',
        ),
    ]
